# Generated by Django 4.0.2 on 2023-06-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_album_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='puede_editar_informacion',
            new_name='puede_gestionar_cargos',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='puede_ver_reportes',
            new_name='puede_gestionar_eventos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_gestionar_galerias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_gestionar_usuarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_gestionar_versiculos',
            field=models.BooleanField(default=False),
        ),
    ]
